
# global:
#   imageRegistry: myRegistryName
#   imagePullSecrets:
#     - myRegistryKeySecretName
#   storageClass: myStorageClass

nameOverride: ""
fullnameOverride: ""

foobar:
  replicas: 1
  annotations: {}
  securityContext: {}

  nodeSelector: {}
  tolerations: []
  affinity: {}

  serviceAccount:
    create: true
    annotations: {}
    name: ""

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  web:
    resources: {}
    image:
      registry: docker.io
      repository: bitnami/nginx
      tag: 1.19.6-debian-10-r1
      pullPolicy: IfNotPresent
      pullSecrets: []

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

certificate:
  dnsName: toto-tata.dm.gg